# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: required
cache:
  - packages
  - ccache
latex: false
warnings_are_errors: false

r:
  - oldrel
  - release
  #- devel

r_packages:
  - methods
  - R6
  - XML
  - httr
  - plyr
  - utils
  - testthat
  - covr

r_build_args: --no-manual
r_check_args: --no-manual --no-build-vignettes --as-cran

after_success:
  - Rscript -e 'library(covr); codecov()'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
